apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-api
  namespace: devops-platform

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-api

  template:
    metadata:
      labels:
        app: devops-api

    spec:
      containers:
        - name: devops-api

          # Replace YOUR_AWS_ACCOUNT_ID and YOUR_IMAGE_TAG before applying.
          # Example: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/devops-cloud-platform:a81f29e
          image: 570934197541.dkr.ecr.ap-south-1.amazonaws.com/devops-cloud-platform:c3639266402ee083ebbfdc017a5767e626fc8f8b

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: devops-api-secrets
                  key: DATABASE_URL

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
