apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devops-cloud-platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Pratik02-07/devops-cloud-platform.git
    targetRevision: main
    path: k8s/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: devops-platform

  syncPolicy:
    automated:
      prune: true      # Remove resources deleted from Git
      selfHeal: true   # Revert any manual changes made directly to the cluster

    syncOptions:
      - CreateNamespace=true
